package PaymentSimpleModel.View;

import PaymentSimpleModel.Controller.AbstractPayment;
import PaymentSimpleModel.Controller.GoldMemberDiscount;
import PaymentSimpleModel.Controller.SpecialDiscount;
import PaymentSimpleModel.Controller.CreditPayment;
import PaymentSimpleModel.Controller.CashPayment;
import PaymentSimpleModel.Controller.CardPayment;
import PaymentSimpleModel.Controller.SilverMemberDiscount;
import PaymentSimpleModel.Controller.BronzeMemberDiscount;
import PaymentSimpleModel.ModelController.ModelController;
import PaymentSimpleModel.Model.*;
import FinanceOptions.Observer.*;
import Cars.View.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;

public class UIPaymentSimpleModel extends javax.swing.JFrame{

    // ********* the variables we'll need **************
    // the main variable to enable the decorator pattern to work
    private CarData carData = new CarData();
    private AbstractPayment payment;
    double getCarPrice;
    String paymentPlan;
    String paymentMethod;
    UICarSales otherForm;
    String aCarType;
    //private JavaDatabaseCRUD javaDatabaseCRUD = new JavaDatabaseCRUD();
    
    // we have to remember the type of object the user has chosen i.e. Card Payment
    // as once a discount has been applied the payment variable  changes into
    // e.g. a GoldDiscount object wrapping around a Card Payment varialbe
    private AbstractPayment currentPayment;
    
        
    // variable for ModelController (to pass the record of the money to the model)
    private ModelController mp;
    private ConnectionToDatabase connectionToDatabase;
    
    // variable to hold the amount the customer paid
    // we get this from the text box
    private Double paid = 0.0;
   
    // helper string variable to hold the value from the text box
    private String getPayment;
    
    
    
    /**
     * Creates new form UIPayment
     */
    public UIPaymentSimpleModel() {
        initComponents();
        setScreen();
    }
    
    public UIPaymentSimpleModel(double getCarPrice, String getCarType , UICarSales otherForm)
    {
        initComponents();
        setScreen();
        
        this.getCarPrice = getCarPrice;
        this.otherForm = otherForm;
        lblgetPayment.setText("" + getCarPrice);
        this.aCarType = getCarType;
        lblgetCar.setText("<html>" + aCarType + "</html>");
        

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupPaymentType = new javax.swing.ButtonGroup();
        btnGroupPaymentDiscounts = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlPayment = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        lblShowPaid = new javax.swing.JLabel();
        lblPaymentPlan = new javax.swing.JLabel();
        lblShowDescription = new javax.swing.JLabel();
        lblgetPayment = new javax.swing.JLabel();
        lblgetCar = new javax.swing.JLabel();
        pnlPayBy = new javax.swing.JPanel();
        rdoCashPayment = new javax.swing.JRadioButton();
        rdoCardPayment = new javax.swing.JRadioButton();
        rdoCreditPayment = new javax.swing.JRadioButton();
        pnlButtons = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnlPaymentPlans = new javax.swing.JPanel();
        btn12Months = new javax.swing.JButton();
        btn24Months = new javax.swing.JButton();
        btn36Months = new javax.swing.JButton();
        btnBuyNow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Payment");
        setMinimumSize(new java.awt.Dimension(200, 28));
        setResizable(false);

        pnlPayment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblPayment.setText("Car Cost : £");
        lblPayment.setName("lblEnterPayment"); // NOI18N

        lblShowPaid.setText("Total Cost : £ 0.00");

        lblPaymentPlan.setText("Payment Plan :");

        lblShowDescription.setText("Type of Payment : ");

        lblgetPayment.setText("...");

        lblgetCar.setText("jLabel1");

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgetCar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaymentPlan)
                    .addComponent(lblShowDescription)
                    .addComponent(lblShowPaid)
                    .addGroup(pnlPaymentLayout.createSequentialGroup()
                        .addComponent(lblPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblgetPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgetCar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment)
                    .addComponent(lblgetPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblShowDescription)
                .addGap(18, 18, 18)
                .addComponent(lblShowPaid)
                .addGap(18, 18, 18)
                .addComponent(lblPaymentPlan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPayBy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnGroupPaymentType.add(rdoCashPayment);
        rdoCashPayment.setText("Cash");
        rdoCashPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashPaymentActionPerformed(evt);
            }
        });

        btnGroupPaymentType.add(rdoCardPayment);
        rdoCardPayment.setText("Debit Card");
        rdoCardPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCardPaymentActionPerformed(evt);
            }
        });

        btnGroupPaymentType.add(rdoCreditPayment);
        rdoCreditPayment.setText("Credit Card");
        rdoCreditPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCreditPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPayByLayout = new javax.swing.GroupLayout(pnlPayBy);
        pnlPayBy.setLayout(pnlPayByLayout);
        pnlPayByLayout.setHorizontalGroup(
            pnlPayByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayByLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoCashPayment)
                .addGap(18, 18, 18)
                .addComponent(rdoCardPayment)
                .addGap(18, 18, 18)
                .addComponent(rdoCreditPayment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPayByLayout.setVerticalGroup(
            pnlPayByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayByLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPayByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCashPayment)
                    .addComponent(rdoCardPayment)
                    .addComponent(rdoCreditPayment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPay.setEnabled(false);
        btnPay.setLabel("Pay");
        btnPay.setName("btnPay"); // NOI18N
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPay)
                .addContainerGap())
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPaymentPlans.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment plans", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btn12Months.setText("12 Months");
        btn12Months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12MonthsActionPerformed(evt);
            }
        });

        btn24Months.setText("24 Months");
        btn24Months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24MonthsActionPerformed(evt);
            }
        });

        btn36Months.setText("36 Months");
        btn36Months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36MonthsActionPerformed(evt);
            }
        });

        btnBuyNow.setText("Buy Now");
        btnBuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentPlansLayout = new javax.swing.GroupLayout(pnlPaymentPlans);
        pnlPaymentPlans.setLayout(pnlPaymentPlansLayout);
        pnlPaymentPlansLayout.setHorizontalGroup(
            pnlPaymentPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentPlansLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuyNow)
                .addGap(18, 18, 18)
                .addComponent(btn12Months)
                .addGap(18, 18, 18)
                .addComponent(btn24Months)
                .addGap(18, 18, 18)
                .addComponent(btn36Months)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentPlansLayout.setVerticalGroup(
            pnlPaymentPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentPlansLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuyNow)
                    .addComponent(btn12Months)
                    .addComponent(btn24Months)
                    .addComponent(btn36Months))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlPayBy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPaymentPlans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPaymentPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPayBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setScreen()
    {
        pnlPaymentPlans.setVisible(true);
        pnlPayBy.setVisible(false);
    }
    
    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        if (!rdoCashPayment.isSelected()&&!rdoCardPayment.isSelected()&&!rdoCreditPayment.isSelected()){
            return;
        } else {
            try {
                // send the payment to the  ModelController (see method below)
                sendToModel();
            } catch (SQLException e) {
                System.err.println("Grr - Cannot connect the database!" + e);
            }
        JOptionPane.showMessageDialog(rootPane, "Payment Complete.");
        otherForm.setEnabled(true);
        otherForm.cleanPage();
        this.dispose();
        }
    }//GEN-LAST:event_btnPayActionPerformed


    private void sendToModel()throws SQLException
    { 
        //Create a new connection to the database
        connectionToDatabase = new ConnectionToDatabase(this.aCarType, getCarPrice, paymentPlan, paymentMethod); 
        connectionToDatabase.addNewRecord();
    }
    

private double roundIt(double d)
        {
            // turn our double value into a BigDecimal variable
            // by passing it to the constructor of our new BigDecimal
            // object named bd
            BigDecimal bd = new BigDecimal(d);
            // now round it up to 2 dec places
            // If we were crooked we could round down - but we'll round up
            BigDecimal rounded = bd.setScale(2, RoundingMode.HALF_UP);
            // now turn the rounded value back to a double
            d = rounded.doubleValue();
            
            // now give it back to the sendToModel method 
            return d;
        }


    private void rdoCardPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCardPaymentActionPerformed
        // If this radio button is selected call the method createPayment
        // and give it a new CardPayment object
        createPaymentType(new CardPayment());
        btnPay.setEnabled(true);
        paymentMethod = payment.getDescription();
    }//GEN-LAST:event_rdoCardPaymentActionPerformed

    private void rdoCreditPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCreditPaymentActionPerformed
        createPaymentType(new CreditPayment());
        btnPay.setEnabled(true);
        paymentMethod = payment.getDescription();
    }//GEN-LAST:event_rdoCreditPaymentActionPerformed

    private void rdoCashPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashPaymentActionPerformed
        createPaymentType(new CashPayment());
        btnPay.setEnabled(true);
        paymentMethod = payment.getDescription();
    }//GEN-LAST:event_rdoCashPaymentActionPerformed

    public void paymentUpdate(double TotalCost, String Plan){
        getCarPrice = TotalCost;
        paymentPlan = Plan;
        lblShowPaid.setText("Total Cost : £ " + TotalCost);
        lblPaymentPlan.setText("Payment Plan : " + Plan);
        btn12Months.setEnabled(false);
        btn24Months.setEnabled(false);
        btn36Months.setEnabled(false);
        btnBuyNow.setEnabled(false);
        pnlPayBy.setVisible(true);
        rdoCashPayment.setEnabled(false);
    }
    /**
     * 
     * @param ap
     * gets passed a new object of type CardPayment, CreditPayment, etc
     * from the radio button methods directly above
     */
    private void createPaymentType(AbstractPayment ap)
    {
        
        // get the payment value from the text box
        getPayment = lblgetPayment.getText();
        

        // get the payment value from the textBox and put it into the variable
        // paid
        // the text box gives us a String variable so we need to change it to a
        // double variable so that we can do some Maths on it if we want to
        paid = Double.parseDouble(getPayment);
       
        // this object just got passed to us - this is the payment type
        // i.e. Card Payment, etc 
        payment = ap;
   
        // check the payment type
        String OType = "" + payment.getClass().getSimpleName();
        
        // now set the payment in the object by calling the setThePayment
        // method and giving it the value from the text box vhanged to a double
        payment.setThePayment(paid);
        
        // keep a record of the current object i.e. CardPayment, CreditPayment
        currentPayment = ap; 
        
        
        // print dtails to the screen
        lblShowDescription.setText("Type of Payment : " + payment.getDescription());
        lblShowPaid.setText("Total Cost : £ " + payment.cost());
    }
    

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        otherForm.setEnabled(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn12MonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12MonthsActionPerformed
        // TODO add your handling code here:
        D12Months d12Months = new D12Months(carData, this);
        carData.setData(getCarPrice, aCarType);
        d12Months.display();
    }//GEN-LAST:event_btn12MonthsActionPerformed

    private void btn24MonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24MonthsActionPerformed
        // TODO add your handling code here:
        D24Months d24Months = new D24Months(carData, this);
        carData.setData(getCarPrice, aCarType);
        d24Months.display();
    }//GEN-LAST:event_btn24MonthsActionPerformed

    private void btnBuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNowActionPerformed
        // TODO add your handling code here:
        
        lblShowPaid.setText("Total Cost : £ " + lblgetPayment.getText());
        lblPaymentPlan.setText("Payment Plan : N/A");
        pnlPayBy.setVisible(true);
        btn12Months.setEnabled(false);
        btn24Months.setEnabled(false);
        btn36Months.setEnabled(false);
        btnBuyNow.setEnabled(false);
    }//GEN-LAST:event_btnBuyNowActionPerformed

    private void btn36MonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36MonthsActionPerformed
        // TODO add your handling code here:
        D36Months d36Months = new D36Months(carData, this);
        carData.setData(getCarPrice, aCarType);
        d36Months.display();
    }//GEN-LAST:event_btn36MonthsActionPerformed

 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPaymentSimpleModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPaymentSimpleModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPaymentSimpleModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPaymentSimpleModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPaymentSimpleModel().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn12Months;
    private javax.swing.JButton btn24Months;
    private javax.swing.JButton btn36Months;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuyNow;
    private javax.swing.ButtonGroup btnGroupPaymentDiscounts;
    private javax.swing.ButtonGroup btnGroupPaymentType;
    private javax.swing.JButton btnPay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPaymentPlan;
    private javax.swing.JLabel lblShowDescription;
    private javax.swing.JLabel lblShowPaid;
    private javax.swing.JLabel lblgetCar;
    private javax.swing.JLabel lblgetPayment;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlPayBy;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlPaymentPlans;
    private javax.swing.JRadioButton rdoCardPayment;
    private javax.swing.JRadioButton rdoCashPayment;
    private javax.swing.JRadioButton rdoCreditPayment;
    // End of variables declaration//GEN-END:variables
}
