/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinanceOptions.View;

import PaymentSimpleModel.View.UIPaymentSimpleModel;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author 32974205
 */
public class FraFinance extends javax.swing.JFrame {
    
    public String carDescription;
    public double carPrice;
    public double totalInterest;
    public double interestRate;
    public double monthlyCost;
    public double totalCost;
    public int numPayments;
    private UIPaymentSimpleModel paymentScreen;
    private String paymentPlan;
    
    /**
     * Creates new form Fra12Months
     */
    public FraFinance() {
        initComponents();
    }
    
    public FraFinance(double CarPrice, String CarDescription, double InterestRate, double MonthlyCost, double TotalCost, int NumPayments, UIPaymentSimpleModel PaymentScreen, String PaymentPlan) {
        
        initComponents();
        this.carPrice = CarPrice;
        this.carDescription = CarDescription;
        this.interestRate = InterestRate;
        this.monthlyCost = MonthlyCost;
        this.totalCost = TotalCost;
        this.numPayments = NumPayments;
        this.paymentScreen = PaymentScreen;
        this.paymentPlan = PaymentPlan;
        
        totalInterest = totalCost - carPrice;
        
        this.carPrice = roundIt(CarPrice);
        this.totalInterest = roundIt(totalInterest);
        this.totalCost = roundIt(totalCost);
        this.monthlyCost = roundIt(monthlyCost);
        
        lblCarDescription.setText("Description: " + carDescription);
        lblCarPrice.setText("Price of Car: £" + carPrice);
        lblInterestRate.setText("Interest Rate: " + interestRate + "%");
        lblTotalCost.setText("Total Cost: £" + totalCost);
        lblTotalInterest.setText("Total Interest: £" + totalInterest);
        lblMonthlyCost.setText("Cost per Month: £" + monthlyCost);
        pnlPaymentPlan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, numPayments + " Month Payment Plan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPaymentPlan = new javax.swing.JPanel();
        lblCarDescription = new javax.swing.JLabel();
        lblCarPrice = new javax.swing.JLabel();
        lblInterestRate = new javax.swing.JLabel();
        lblTotalInterest = new javax.swing.JLabel();
        lblMonthlyCost = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPaymentPlan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "12 Month Payment Plan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblCarDescription.setText("Description");

        lblCarPrice.setText("Price");

        lblInterestRate.setText("Interest Rate");

        lblTotalInterest.setText("Total Interest");

        lblMonthlyCost.setText("Monthly Cost");

        lblTotalCost.setText("Total Cost");

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentPlanLayout = new javax.swing.GroupLayout(pnlPaymentPlan);
        pnlPaymentPlan.setLayout(pnlPaymentPlanLayout);
        pnlPaymentPlanLayout.setHorizontalGroup(
            pnlPaymentPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentPlanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTotalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMonthlyCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalInterest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(lblInterestRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPaymentPlanLayout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addComponent(lblCarDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentPlanLayout.setVerticalGroup(
            pnlPaymentPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentPlanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCarPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInterestRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalInterest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMonthlyCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalCost)
                .addGap(18, 18, 18)
                .addGroup(pnlPaymentPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaymentPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaymentPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        paymentScreen.paymentUpdate(totalCost, paymentPlan);
        paymentScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    private double roundIt (double price){
    BigDecimal bd = new BigDecimal(price);
    BigDecimal rounded = bd.setScale(2, RoundingMode.HALF_UP);
    price = rounded.doubleValue();
    return price;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraFinance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FraFinance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblCarDescription;
    private javax.swing.JLabel lblCarPrice;
    private javax.swing.JLabel lblInterestRate;
    private javax.swing.JLabel lblMonthlyCost;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel lblTotalInterest;
    private javax.swing.JPanel pnlPaymentPlan;
    // End of variables declaration//GEN-END:variables
}
