/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cars.View;

import Staff.*;
import CarSelection.Controller.CRV;
import CarSelection.Controller.AbCar;
import CarSelection.Controller.HRV;
import CarSelection.Controller.Alloys;
import CarSelection.Controller.Bluetooth;
import CarSelection.Controller.Civic;
import CarSelection.Controller.Sunroof;
import CarSelection.Controller.SatNav;
import CarSelection.Controller.Leather;
import CarSelection.Controller.HeatedSeats;
import CarSelection.Controller.Jazz;
import CarSelection.Controller.Metalic;
import PaymentSimpleModel.Controller.*;
import PaymentSimpleModel.Model.*;
import PaymentSimpleModel.ModelController.*;
import PaymentSimpleModel.View.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
/**
 *
 * @author 32974205
 */
public class UICarSales extends javax.swing.JFrame {

    /**
     * Creates new form UICarSales
     */
    
    AbCar car;
    UIPaymentSimpleModel NewPaymentScreen;
    AbstractPayment CarPayment;
    public double price;
    public String colour;
    public String carType;
    
    private double roundIt (double price){
    BigDecimal bd = new BigDecimal(price);
    BigDecimal rounded = bd.setScale(2, RoundingMode.HALF_UP);
    price = rounded.doubleValue();
    return price;
    }
    
    public UICarSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpColour = new javax.swing.ButtonGroup();
        pnlCarSelect = new javax.swing.JPanel();
        comboCarType = new javax.swing.JComboBox<>();
        pnlSelectIntAddOns = new javax.swing.JPanel();
        chkboxHetaedSeats = new javax.swing.JCheckBox();
        chkboxLeather = new javax.swing.JCheckBox();
        chkboxSatNav = new javax.swing.JCheckBox();
        chkboxBluetooth = new javax.swing.JCheckBox();
        pnlSelectExtAddOns = new javax.swing.JPanel();
        chkboxMetalic = new javax.swing.JCheckBox();
        chkboxAlloys = new javax.swing.JCheckBox();
        chkboxSunroof = new javax.swing.JCheckBox();
        Colour = new javax.swing.JPanel();
        rdobtnRed = new javax.swing.JRadioButton();
        rdobtnBlue = new javax.swing.JRadioButton();
        rdobtnBlack = new javax.swing.JRadioButton();
        rdobtnWhite = new javax.swing.JRadioButton();
        pnlLabel = new javax.swing.JPanel();
        lblSelectedCar = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnForm = new javax.swing.JButton();
        btnStaffLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Your Car.");
        setIconImages(null);
        setResizable(false);

        pnlCarSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        comboCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civic", "Jazz", "CR-V", "HR-V" }));
        comboCarType.setToolTipText("Select Car");
        comboCarType.setName(""); // NOI18N

        javax.swing.GroupLayout pnlCarSelectLayout = new javax.swing.GroupLayout(pnlCarSelect);
        pnlCarSelect.setLayout(pnlCarSelectLayout);
        pnlCarSelectLayout.setHorizontalGroup(
            pnlCarSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCarType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCarSelectLayout.setVerticalGroup(
            pnlCarSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSelectIntAddOns.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Interior Add ons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        chkboxHetaedSeats.setText("Heated Seats");

        chkboxLeather.setText("Leather");

        chkboxSatNav.setText("Sat-Nav");

        chkboxBluetooth.setText("Bluetooth");

        javax.swing.GroupLayout pnlSelectIntAddOnsLayout = new javax.swing.GroupLayout(pnlSelectIntAddOns);
        pnlSelectIntAddOns.setLayout(pnlSelectIntAddOnsLayout);
        pnlSelectIntAddOnsLayout.setHorizontalGroup(
            pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectIntAddOnsLayout.createSequentialGroup()
                .addGroup(pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkboxHetaedSeats)
                    .addComponent(chkboxSatNav))
                .addGap(24, 24, 24)
                .addGroup(pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkboxBluetooth)
                    .addComponent(chkboxLeather))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSelectIntAddOnsLayout.setVerticalGroup(
            pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectIntAddOnsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkboxHetaedSeats)
                    .addComponent(chkboxLeather))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSelectIntAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkboxSatNav)
                    .addComponent(chkboxBluetooth)))
        );

        pnlSelectExtAddOns.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Exterior Add-ons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        chkboxMetalic.setText("Metalic");

        chkboxAlloys.setText("Alloys");

        chkboxSunroof.setText("Sunroof");

        javax.swing.GroupLayout pnlSelectExtAddOnsLayout = new javax.swing.GroupLayout(pnlSelectExtAddOns);
        pnlSelectExtAddOns.setLayout(pnlSelectExtAddOnsLayout);
        pnlSelectExtAddOnsLayout.setHorizontalGroup(
            pnlSelectExtAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectExtAddOnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectExtAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSelectExtAddOnsLayout.createSequentialGroup()
                        .addComponent(chkboxSunroof)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSelectExtAddOnsLayout.createSequentialGroup()
                        .addComponent(chkboxMetalic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkboxAlloys)
                        .addGap(37, 37, 37))))
        );
        pnlSelectExtAddOnsLayout.setVerticalGroup(
            pnlSelectExtAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectExtAddOnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectExtAddOnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkboxMetalic)
                    .addComponent(chkboxAlloys))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkboxSunroof)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Colour.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btngrpColour.add(rdobtnRed);
        rdobtnRed.setText("Red");

        btngrpColour.add(rdobtnBlue);
        rdobtnBlue.setText("Blue");

        btngrpColour.add(rdobtnBlack);
        rdobtnBlack.setText("Black");

        btngrpColour.add(rdobtnWhite);
        rdobtnWhite.setText("White");

        javax.swing.GroupLayout ColourLayout = new javax.swing.GroupLayout(Colour);
        Colour.setLayout(ColourLayout);
        ColourLayout.setHorizontalGroup(
            ColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdobtnRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdobtnBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdobtnWhite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdobtnBlack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ColourLayout.setVerticalGroup(
            ColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdobtnRed)
                    .addComponent(rdobtnBlue)
                    .addComponent(rdobtnWhite)
                    .addComponent(rdobtnBlack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSelectedCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedCar.setText("Select your car");
        lblSelectedCar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectedCar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectedCar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnForm.setText("Checkout");
        btnForm.setEnabled(false);
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormActionPerformed(evt);
            }
        });

        btnStaffLogIn.setText("Staff Log In");
        btnStaffLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStaffLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnForm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnExit)
                    .addComponent(btnForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaffLogIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSelectExtAddOns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSelectIntAddOns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Colour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCarSelect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCarSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Colour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSelectIntAddOns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSelectExtAddOns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    public void cleanPage(){
        UICarSales newCarSales = new UICarSales();
        newCarSales.setVisible(true);
        this.dispose();
    }
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        //////////////////////////////////////////////
        //Check Colour is selected
        //////////////////////////////////////////////
        if (!rdobtnBlack.isSelected() && !rdobtnBlue.isSelected() && !rdobtnRed.isSelected() && !rdobtnWhite.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Please select a colour.");
            return;
        }
        //////////////////////////////////////
        //Car Selecter
        //////////////////////////////////////
        String chosenCar = comboCarType.getSelectedItem().toString();
        if (chosenCar.equals("Civic")){
            car = new Civic();
        }
        if (chosenCar.equals("Jazz")){
            car = new Jazz();
        }
        if (chosenCar.equals("HR-V")){
            car = new HRV();
        }
        if (chosenCar.equals("CR-V")){
            car = new CRV();
        }
        //////////////////////////////////////////////////////////
        //Colour Selecter
        //////////////////////////////////////////////////////////
        if (rdobtnBlack.isSelected()){
            colour = "Black";
        }
        if (rdobtnBlue.isSelected()){
            colour = "Blue";
        }
        if (rdobtnRed.isSelected()){
            colour = "Red";
        }
        if (rdobtnWhite.isSelected()){
            colour = "White";
        }
        ///////////////////////////////////////////////////////////////////
        //Interior add-ons
        ///////////////////////////////////////////////////////////////////
        if (chkboxBluetooth.isSelected()){
            car = new Bluetooth(car);
        }
        if (chkboxHetaedSeats.isSelected()){
            car = new HeatedSeats(car);
        }
        if (chkboxSatNav.isSelected()){
            car = new SatNav(car);
        }
        if (chkboxLeather.isSelected()){
            car = new Leather(car);
        }
        ///////////////////////////////////////////////////////////////
        //exterior add-ons
        ///////////////////////////////////////////////////////////////
        if (chkboxAlloys.isSelected()){
            car = new Alloys(car);
        }
        if (chkboxMetalic.isSelected()){
            car = new Metalic(car);
        }
        if (chkboxSunroof.isSelected()){
            car = new Sunroof(car);
        }
        ///////////////////////////////////////////////////////////////////
        //Get The price into standard money form
        ///////////////////////////////////////////////////////////////////
        price = roundIt(car.cost());
        ///////////////////////////////////////////////////////////////////
        //Set the label
        ///////////////////////////////////////////////////////////////////
        carType = car.getDescription() + " in " + car.getColour(colour);
        String labelText = car.getDescription() + " in " + car.getColour(colour) + ". Total Cost = £" + price;
        lblSelectedCar.setText("<html>" + labelText + "</html>");
        btnForm.setEnabled(true);
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormActionPerformed
        // TODO add your handling code here:
        NewPaymentScreen = new UIPaymentSimpleModel(price, carType , this);
        NewPaymentScreen.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnFormActionPerformed

    private void btnStaffLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLogInActionPerformed
        FraStafLogInView staffLogIn = new FraStafLogInView();
        staffLogIn.setVisible(true);
    }//GEN-LAST:event_btnStaffLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICarSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICarSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Colour;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnForm;
    private javax.swing.JButton btnStaffLogIn;
    private javax.swing.ButtonGroup btngrpColour;
    private javax.swing.JCheckBox chkboxAlloys;
    private javax.swing.JCheckBox chkboxBluetooth;
    private javax.swing.JCheckBox chkboxHetaedSeats;
    private javax.swing.JCheckBox chkboxLeather;
    private javax.swing.JCheckBox chkboxMetalic;
    private javax.swing.JCheckBox chkboxSatNav;
    private javax.swing.JCheckBox chkboxSunroof;
    private javax.swing.JComboBox<String> comboCarType;
    private javax.swing.JLabel lblSelectedCar;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCarSelect;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlSelectExtAddOns;
    private javax.swing.JPanel pnlSelectIntAddOns;
    private javax.swing.JRadioButton rdobtnBlack;
    private javax.swing.JRadioButton rdobtnBlue;
    private javax.swing.JRadioButton rdobtnRed;
    private javax.swing.JRadioButton rdobtnWhite;
    // End of variables declaration//GEN-END:variables
}
